theme = "monokai_pro_octagon"

[editor]
auto-completion = false
cursorline = true
idle-timeout = 400
line-number = "relative"
middle-click-paste = false
mouse = false
rulers = [100]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
newline = "all"
space = "all"
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "◀"

[keys.normal]
n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"

l = "insert_mode"
u = "open_below"
U = "open_above"
h = "search_next"
H = "search_prev"
j = "undo"
J = "redo"
