theme = "monokai_pro_octagon"

[editor]
auto-completion = false
cursorline = true
color-modes = true
idle-timeout = 400
line-number = "relative"
middle-click-paste = false
mouse = false
rulers = [100]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.whitespace.render]
newline = "all"
space = "all"
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "◀"
