theme = "sonokai"

[editor]
auto-completion = true
bufferline = "always"
cursorline = true
color-modes = true
idle-timeout = 400
line-number = "relative"
middle-click-paste = false
mouse = false
rulers = [100]
true-color = true
scrolloff = 10

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "┆"
skip-levels = 1
render = true

[editor.statusline]
right = ["diagnostics", "selections", "primary-selection-length", "position", "total-line-numbers", "file-encoding"]

[editor.whitespace.render]
newline = "all"
space = "all"
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "◀"

[keys.normal]
X = "extend_line_above"
