theme = "catppuccin_mocha"

[editor]
auto-completion = true
bufferline = "always"
color-modes = true
cursorline = true
idle-timeout = 200
insert-final-newline = true
line-number = "relative"
middle-click-paste = false
mouse = false
rulers = [100, 160]
scrolloff = 10
text-width = 160
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true
display-messages = true
display-signature-help-docs = true
snippets = true

[editor.indent-guides]
character = "┆"
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = "↪"

[editor.statusline]
right = [
  "diagnostics",
  "file-encoding",
  "position",
  "total-line-numbers",
  "separator",
  "register",
  "separator",
  "primary-selection-length",
  "selections",
]

[editor.whitespace.render]
newline = "all"
space = "all"
tab = "all"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "◀"
space = "·"
tab = "→"

[keys.normal]
C-down = "shrink_selection"
C-left = "select_prev_sibling"
C-right = "select_next_sibling"
C-up = "expand_selection"
X = "extend_line_above"
