[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
text-width = 160

[[language]]
name = "html"
indent = { tab-width = 2, unit = "  " }
text-width = 160

[[language]]
name = "nu"
indent = { tab-width = 2, unit = "    " }
text-width = 160

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }
text-width = 160

[[language]]
name = "rust"
text-width = 160
language-servers = ["rust-analyzer"]
soft-wrap.enable = false
# language-servers = ["scls", "rust-analyzer"]

# [language-server.scls]
# command = "simple-completion-language-server"
# config = { max_completion_items = 20, snippets_first = false }

# [language-server.scls.environment]
# RUST_LOG = "deubg,simple-completion-language-server=debug"
# LOG_FILE = "/tmp/completion.log"

[language-server.rust-analyzer.config]
checkOnSave = { enabled = true, command = "check" }
# checkOnSave = { extraArgs = ["---profile", "rust-analyzer"] }
# check = { extraArgs = ["---profile", "rust-analyzer"] }
inlayHints.parameterHints.enable = false
inlayHints.closingBraceHints.minLines = 10
# workspace.symbol.search.kind = "all_symbols"
# workspace.symbol.search.limit = 65536
# procMacro.enable = false
# dignostics.experimental.enable = false
# diagnostics.disabled = ["unresolved-proc-macro"]

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"

[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[language]]
name = "toml"
text-width = 160

[[language]]
name = "c"
text-width = 160

[[language]]
name = "sql"
indent = { tab-width = 2, unit = "  " }
text-width = 160
