[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
indent = { tab-width = 2, unit = "    " }

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }
