[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
indent = { tab-width = 2, unit = "    " }

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true